################################################################################
#
# This file has been generated by SpyGlass:
#     Report Created by: ulisses.maffazioli
#     Report Created on: Tue Jul 14 00:04:14 2026
#     Working Directory: /home/mic63/ulisses.maffazioli/dft-labs/proj/santiago_cpu/0_synopsys_saed32_flow/dft/6_advisor_rtl_naive
#     Report Location  : ./out_data/naive_comb/top/dft/dft_scan_ready/spyglass_reports/dft/dft_generated_dc_constraints.tcl
#     SpyGlass Version : SpyGlass_vW-2024.09-SP2-8
#     Policy Name      : dft(SpyGlass_vW-2024.09-SP2-08)
#     Comment          : Generated by rule Info_generated_reports
#
################################################################################

################################################################################
# Begin data for design unit: top
################################################################################

 current_design top
################################################################################
# End data for design unit: top
################################################################################

