################################################################################
#
# This file has been generated by SpyGlass:
#     Report Created by: ulisses.maffazioli
#     Report Created on: Mon Jul 13 11:38:40 2026
#     Working Directory: /home/mic63/ulisses.maffazioli/dft-labs/proj/santiago_cpu/0_synopsys_saed32_flow/dft/advisor_flow_naive
#     Report Location  : ./out_data/naive_comb/top/dft/dft_dsm_random_resistance/spyglass_reports/dft/dft_generated_dc_constraints.tcl
#     SpyGlass Version : SpyGlass_vW-2024.09-SP2-8
#     Policy Name      : dft(SpyGlass_vW-2024.09-SP2-08)
#     Comment          : Generated by rule Info_generated_reports
#
################################################################################

################################################################################
# Begin data for design unit: top
################################################################################

 current_design top
################################################################################
# End data for design unit: top
################################################################################

