################################################################################
#
# This file has been generated by SpyGlass:
#     Report Created by: ulisses.maffazioli
#     Report Created on: Sun Jul 12 22:09:17 2026
#     Working Directory: /home/mic63/ulisses.maffazioli/dft-labs/proj/santiago_cpu/0_synopsys_saed32_flow/_dft/advisor_flow
#     Report Location  : ./out_data/santiago/top_santiago_cpu/dft/dft_dsm_random_resistance/spyglass_reports/dft/dft_generated_dc_constraints.tcl
#     SpyGlass Version : SpyGlass_vW-2024.09-SP2-8
#     Policy Name      : dft(SpyGlass_vW-2024.09-SP2-08)
#     Comment          : Generated by rule Info_generated_reports
#
################################################################################

################################################################################
# Begin data for design unit: top_santiago_cpu
################################################################################

 current_design top_santiago_cpu
  set_dft_signal -type MasterClock -port clk -timing [list 45 55]
  set_dft_signal -type Reset -port rst -active_state 1
  set_boundary_cell -type none -port clk
  set_boundary_cell -type none -port rst
################################################################################
# End data for design unit: top_santiago_cpu
################################################################################

