//This is a temporary file generated by spyglass Lib2V utility from the library
//<saed32rvt_tt1p05v25c.lib>. Do not modify this or use this.
//spyglass xref filename </home/mic63/ulisses.maffazioli/dft-labs/proj/santiago_cpu/0_synopsys_saed32_flow/_dft/advisor_flow_netlist/./out_data/santiago/top_santiago_cpu/dft/dft_scan_ready/spyglass_spysch/spyglass/saed32rvt_tt1p05v25c_0.v>
//spyglass xref version SpyGlass_vW-2024.09-SP2-8

//spyglass xref lineno 1286, -1
`celldefine
module AND2X1_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1637, -1
`celldefine
module AND2X2_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1988, -1
`celldefine
module AND2X4_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2339, -1
`celldefine
module AND3X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2927, -1
`celldefine
module AND3X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3515, -1
`celldefine
module AND3X4_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4103, -1
`celldefine
module AND4X1_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5076, -1
`celldefine
module AND4X2_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6049, -1
`celldefine
module AND4X4_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7022, -1
`celldefine
module ANTENNA_RVT (INP);
    input  INP;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7054, -1
`celldefine
module AO21X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7620, -1
`celldefine
module AO21X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 8186, -1
`celldefine
module AO221X1_RVT (A1, A2, A3, A4, A5, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 9708, -1
`celldefine
module AO221X2_RVT (A1, A2, A3, A4, A5, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 11230, -1
`celldefine
module AO222X1_RVT (A1, A2, A3, A4, A5, A6, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    input  A6;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 13893, -1
`celldefine
module AO222X2_RVT (A1, A2, A3, A4, A5, A6, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    input  A6;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 16556, -1
`celldefine
module AO22X1_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 17441, -1
`celldefine
module AO22X2_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 18326, -1
`celldefine
module AOBUFX1_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 18499, -1
`celldefine
module AOBUFX2_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 18672, -1
`celldefine
module AOBUFX4_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 18845, -1
`celldefine
module AODFFARX1_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 19373, -1
`celldefine
module AODFFARX2_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 19901, -1
`celldefine
module AODFFNARX1_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 20429, -1
`celldefine
module AODFFNARX2_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 20957, -1
`celldefine
module AOI21X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 21523, -1
`celldefine
module AOI21X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 22089, -1
`celldefine
module AOI221X1_RVT (A1, A2, A3, A4, A5, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 23611, -1
`celldefine
module AOI221X2_RVT (A1, A2, A3, A4, A5, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 25133, -1
`celldefine
module AOI222X1_RVT (A1, A2, A3, A4, A5, A6, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    input  A6;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 27796, -1
`celldefine
module AOI222X2_RVT (A1, A2, A3, A4, A5, A6, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    input  A6;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 30459, -1
`celldefine
module AOI22X1_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 31344, -1
`celldefine
module AOI22X2_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 32229, -1
`celldefine
module AOINVX1_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 32402, -1
`celldefine
module AOINVX2_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 32575, -1
`celldefine
module AOINVX4_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 32748, -1
`celldefine
module BSLEX1_RVT (INOUT1, EN, INOUT2);
    inout  INOUT1;
    input  EN;
    inout  INOUT2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 33084, -1
`celldefine
module BSLEX2_RVT (INOUT1, EN, INOUT2);
    inout  INOUT1;
    input  EN;
    inout  INOUT2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 33420, -1
`celldefine
module BSLEX4_RVT (INOUT1, EN, INOUT2);
    inout  INOUT1;
    input  EN;
    inout  INOUT2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 33756, -1
`celldefine
module BUSKP_RVT (A);
    input  A;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 33797, -1
`celldefine
module CGLNPRX2_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 34311, -1
`celldefine
module CGLNPRX8_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 34825, -1
`celldefine
module CGLNPSX16_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 35297, -1
`celldefine
module CGLNPSX2_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 35769, -1
`celldefine
module CGLNPSX4_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 36241, -1
`celldefine
module CGLNPSX8_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 36713, -1
`celldefine
module CGLPPRX2_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 37228, -1
`celldefine
module CGLPPRX8_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 37743, -1
`celldefine
module CGLPPSX16_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 38215, -1
`celldefine
module CGLPPSX2_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 38687, -1
`celldefine
module CGLPPSX4_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 39159, -1
`celldefine
module CGLPPSX8_RVT (SE, EN, CLK, GCLK, ENL);
    input  SE;
    input  EN;
    input  CLK;
    output GCLK;
    inout  ENL;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 39631, -1
`celldefine
module CLOAD1_RVT (A);
    input  A;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 39672, -1
`celldefine
module DCAP_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 39688, -1
`celldefine
module DEC24X1_RVT (A0, A1, Y0, Y1, Y2, Y3);
    input  A0;
    input  A1;
    output Y0;
    output Y1;
    output Y2;
    output Y3;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 40801, -1
`celldefine
module DEC24X2_RVT (A0, A1, Y0, Y1, Y2, Y3);
    input  A0;
    input  A1;
    output Y0;
    output Y1;
    output Y2;
    output Y3;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 41914, -1
`celldefine
module DELLN1X2_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 42032, -1
`celldefine
module DELLN2X2_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 42150, -1
`celldefine
module DELLN3X2_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 42268, -1
`celldefine
module DFFARX1_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 42916, -1
`celldefine
module DFFARX2_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 43564, -1
`celldefine
module DFFASRX1_RVT (D, CLK, RSTB, SETB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 44585, -1
`celldefine
module DFFASRX2_RVT (D, CLK, RSTB, SETB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 45606, -1
`celldefine
module DFFASX1_RVT (D, CLK, SETB, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 46243, -1
`celldefine
module DFFASX2_RVT (D, CLK, SETB, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 46880, -1
`celldefine
module DFFNARX1_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 47525, -1
`celldefine
module DFFNARX2_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 48170, -1
`celldefine
module DFFNASRNX1_RVT (D, CLK, RSTB, SETB, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 48962, -1
`celldefine
module DFFNASRNX2_RVT (D, CLK, RSTB, SETB, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 49754, -1
`celldefine
module DFFNASRQX1_RVT (D, CLK, RSTB, SETB, Q);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 50546, -1
`celldefine
module DFFNASRQX2_RVT (D, CLK, RSTB, SETB, Q);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 51338, -1
`celldefine
module DFFNASRX1_RVT (D, CLK, RSTB, SETB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 52359, -1
`celldefine
module DFFNASRX2_RVT (D, CLK, RSTB, SETB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 53380, -1
`celldefine
module DFFNASX1_RVT (D, CLK, SETB, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 54014, -1
`celldefine
module DFFNASX2_RVT (D, CLK, SETB, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 54648, -1
`celldefine
module DFFNX1_RVT (D, CLK, Q, QN);
    input  D;
    input  CLK;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 55126, -1
`celldefine
module DFFNX2_RVT (D, CLK, Q, QN);
    input  D;
    input  CLK;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 55604, -1
`celldefine
module DFFSSRX1_RVT (CLK, D, RSTB, SETB, Q, QN);
    input  CLK;
    input  D;
    input  RSTB;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 56169, -1
`celldefine
module DFFSSRX2_RVT (CLK, D, RSTB, SETB, Q, QN);
    input  CLK;
    input  D;
    input  RSTB;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 56734, -1
`celldefine
module DFFX1_RVT (D, CLK, Q, QN);
    input  D;
    input  CLK;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 57211, -1
`celldefine
module DFFX2_RVT (D, CLK, Q, QN);
    input  D;
    input  CLK;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 57688, -1
`celldefine
module DHFILLH2_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 57704, -1
`celldefine
module DHFILLHL2_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 57720, -1
`celldefine
module DHFILLHLHLS11_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 57740, -1
`celldefine
module FADDX1_RVT (A, B, CI, S, CO);
    input  A;
    input  B;
    input  CI;
    output S;
    output CO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 58785, -1
`celldefine
module FADDX2_RVT (A, B, CI, S, CO);
    input  A;
    input  B;
    input  CI;
    output S;
    output CO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 59830, -1
`celldefine
module HADDX1_RVT (A0, B0, SO, C1);
    input  A0;
    input  B0;
    output SO;
    output C1;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 60533, -1
`celldefine
module HADDX2_RVT (A0, B0, SO, C1);
    input  A0;
    input  B0;
    output SO;
    output C1;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 61236, -1
`celldefine
module IBUFFX16_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 61349, -1
`celldefine
module IBUFFX2_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 61462, -1
`celldefine
module IBUFFX32_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 61575, -1
`celldefine
module IBUFFX4_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 61688, -1
`celldefine
module IBUFFX8_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 61801, -1
`celldefine
module INVX0_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 61916, -1
`celldefine
module INVX16_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 62031, -1
`celldefine
module INVX1_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 62146, -1
`celldefine
module INVX2_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 62261, -1
`celldefine
module INVX32_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 62376, -1
`celldefine
module INVX4_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 62491, -1
`celldefine
module INVX8_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 62606, -1
`celldefine
module ISOLANDAOX1_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 62869, -1
`celldefine
module ISOLANDAOX2_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 63132, -1
`celldefine
module ISOLANDAOX4_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 63395, -1
`celldefine
module ISOLANDAOX8_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 63658, -1
`celldefine
module ISOLANDX1_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 64013, -1
`celldefine
module ISOLANDX2_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 64368, -1
`celldefine
module ISOLANDX4_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 64723, -1
`celldefine
module ISOLANDX8_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 65078, -1
`celldefine
module ISOLORAOX1_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 65341, -1
`celldefine
module ISOLORAOX2_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 65604, -1
`celldefine
module ISOLORAOX4_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 65867, -1
`celldefine
module ISOLORAOX8_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 66130, -1
`celldefine
module ISOLORX1_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 66485, -1
`celldefine
module ISOLORX2_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 66840, -1
`celldefine
module ISOLORX4_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 67195, -1
`celldefine
module ISOLORX8_RVT (ISO, D, Q);
    input  ISO;
    input  D;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 67550, -1
`celldefine
module LARX1_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 68172, -1
`celldefine
module LARX2_RVT (D, CLK, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 68794, -1
`celldefine
module LASRNX1_RVT (D, CLK, SETB, RSTB, QN);
    input  D;
    input  CLK;
    input  SETB;
    input  RSTB;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 69746, -1
`celldefine
module LASRNX2_RVT (D, CLK, SETB, RSTB, QN);
    input  D;
    input  CLK;
    input  SETB;
    input  RSTB;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 70698, -1
`celldefine
module LASRQX1_RVT (D, CLK, SETB, RSTB, Q);
    input  D;
    input  CLK;
    input  SETB;
    input  RSTB;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 71265, -1
`celldefine
module LASRQX2_RVT (D, CLK, SETB, RSTB, Q);
    input  D;
    input  CLK;
    input  SETB;
    input  RSTB;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 71832, -1
`celldefine
module LASRX1_RVT (D, CLK, SETB, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 72682, -1
`celldefine
module LASRX2_RVT (D, CLK, SETB, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 73532, -1
`celldefine
module LASX1_RVT (D, CLK, SETB, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 74154, -1
`celldefine
module LASX2_RVT (D, CLK, SETB, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 74776, -1
`celldefine
module LATCHX1_RVT (D, CLK, Q, QN);
    input  D;
    input  CLK;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 75194, -1
`celldefine
module LATCHX2_RVT (D, CLK, Q, QN);
    input  D;
    input  CLK;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 75612, -1
`celldefine
module LNANDX1_RVT (SIN, RIN, Q, QN);
    input  SIN;
    input  RIN;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 75949, -1
`celldefine
module LNANDX2_RVT (SIN, RIN, Q, QN);
    input  SIN;
    input  RIN;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 76286, -1
`celldefine
module MUX21X1_RVT (A1, A2, S0, Y);
    input  A1;
    input  A2;
    input  S0;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 76633, -1
`celldefine
module MUX21X2_RVT (A1, A2, S0, Y);
    input  A1;
    input  A2;
    input  S0;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 76980, -1
`celldefine
module MUX41X1_RVT (A1, A2, A3, A4, S0, S1, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  S0;
    input  S1;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 77645, -1
`celldefine
module MUX41X2_RVT (A1, A2, A3, A4, S0, S1, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  S0;
    input  S1;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 78310, -1
`celldefine
module NAND2X0_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 78661, -1
`celldefine
module NAND2X1_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 79012, -1
`celldefine
module NAND2X2_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 79363, -1
`celldefine
module NAND2X4_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 79714, -1
`celldefine
module NAND3X0_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 80302, -1
`celldefine
module NAND3X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 80890, -1
`celldefine
module NAND3X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 81478, -1
`celldefine
module NAND3X4_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 82066, -1
`celldefine
module NAND4X0_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 83039, -1
`celldefine
module NAND4X1_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84012, -1
`celldefine
module NBUFFX16_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84125, -1
`celldefine
module NBUFFX2_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84238, -1
`celldefine
module NBUFFX32_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84351, -1
`celldefine
module NBUFFX4_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84464, -1
`celldefine
module NBUFFX8_RVT (A, Y);
    input  A;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84577, -1
`celldefine
module NMT1_RVT (G, D, S);
    input  G;
    output D;
    inout  S;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84628, -1
`celldefine
module NMT2_RVT (G, D, S);
    input  G;
    output D;
    inout  S;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84679, -1
`celldefine
module NMT3_RVT (G, D, S);
    input  G;
    output D;
    inout  S;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 84730, -1
`celldefine
module NOR2X0_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 85081, -1
`celldefine
module NOR2X1_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 85432, -1
`celldefine
module NOR2X2_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 85783, -1
`celldefine
module NOR2X4_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 86134, -1
`celldefine
module NOR3X0_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 86722, -1
`celldefine
module NOR3X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 87310, -1
`celldefine
module NOR3X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 87898, -1
`celldefine
module NOR3X4_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 88486, -1
`celldefine
module NOR4X0_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 89459, -1
`celldefine
module NOR4X1_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 90432, -1
`celldefine
module OA21X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 90998, -1
`celldefine
module OA21X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 91564, -1
`celldefine
module OA221X1_RVT (A1, A2, A3, A4, A5, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 93086, -1
`celldefine
module OA221X2_RVT (A1, A2, A3, A4, A5, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 94608, -1
`celldefine
module OA222X1_RVT (A1, A2, A3, A4, A5, A6, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    input  A6;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 97271, -1
`celldefine
module OA222X2_RVT (A1, A2, A3, A4, A5, A6, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    input  A6;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 99934, -1
`celldefine
module OA22X1_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 100819, -1
`celldefine
module OA22X2_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 101704, -1
`celldefine
module OAI21X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 102270, -1
`celldefine
module OAI21X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 102836, -1
`celldefine
module OAI221X1_RVT (A1, A2, A3, A4, A5, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 104358, -1
`celldefine
module OAI221X2_RVT (A1, A2, A3, A4, A5, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 105880, -1
`celldefine
module OAI222X1_RVT (A1, A2, A3, A4, A5, A6, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    input  A6;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 108543, -1
`celldefine
module OAI222X2_RVT (A1, A2, A3, A4, A5, A6, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    input  A5;
    input  A6;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 111206, -1
`celldefine
module OAI22X1_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 112091, -1
`celldefine
module OAI22X2_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 112976, -1
`celldefine
module OR2X1_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 113327, -1
`celldefine
module OR2X2_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 113678, -1
`celldefine
module OR2X4_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 114029, -1
`celldefine
module OR3X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 114617, -1
`celldefine
module OR3X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 115205, -1
`celldefine
module OR3X4_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 115793, -1
`celldefine
module OR4X1_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 116766, -1
`celldefine
module OR4X2_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 117739, -1
`celldefine
module OR4X4_RVT (A1, A2, A3, A4, Y);
    input  A1;
    input  A2;
    input  A3;
    input  A4;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 118712, -1
`celldefine
module PGX1_RVT (INOUT1, AN, AP, INOUT2);
    inout  INOUT1;
    input  AN;
    input  AP;
    inout  INOUT2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 119147, -1
`celldefine
module PGX2_RVT (INOUT1, AN, AP, INOUT2);
    inout  INOUT1;
    input  AN;
    input  AP;
    inout  INOUT2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 119582, -1
`celldefine
module PGX4_RVT (INOUT1, AN, AP, INOUT2);
    inout  INOUT1;
    input  AN;
    input  AP;
    inout  INOUT2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 120017, -1
`celldefine
module PMT1_RVT (G, D, S);
    input  G;
    output D;
    inout  S;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 120068, -1
`celldefine
module PMT2_RVT (G, D, S);
    input  G;
    output D;
    inout  S;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 120119, -1
`celldefine
module PMT3_RVT (G, D, S);
    input  G;
    output D;
    inout  S;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 120170, -1
`celldefine
module RDFFARX1_RVT (D, CLK, RETN, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 120807, -1
`celldefine
module RDFFARX2_RVT (D, CLK, RETN, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 121444, -1
`celldefine
module RDFFNARX1_RVT (D, CLK, RETN, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 122076, -1
`celldefine
module RDFFNARX2_RVT (D, CLK, RETN, RSTB, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  RSTB;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 122708, -1
`celldefine
module RDFFNSRARX1_RVT (RSTB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 123591, -1
`celldefine
module RDFFNSRARX2_RVT (RSTB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 124474, -1
`celldefine
module RDFFNSRASRNX1_RVT (RSTB, SETB, CLK, D, NRESTORE, QN, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 125710, -1
`celldefine
module RDFFNSRASRNX2_RVT (RSTB, SETB, CLK, D, NRESTORE, QN, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 126946, -1
`celldefine
module RDFFNSRASRQX1_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 128186, -1
`celldefine
module RDFFNSRASRQX2_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 129426, -1
`celldefine
module RDFFNSRASRX1_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 130688, -1
`celldefine
module RDFFNSRASRX2_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 131950, -1
`celldefine
module RDFFNSRASX1_RVT (SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 132804, -1
`celldefine
module RDFFNSRASX2_RVT (SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 133658, -1
`celldefine
module RDFFNSRX1_RVT (CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 134219, -1
`celldefine
module RDFFNSRX2_RVT (CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 134780, -1
`celldefine
module RDFFNX1_RVT (D, CLK, RETN, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 135090, -1
`celldefine
module RDFFNX2_RVT (D, CLK, RETN, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 135400, -1
`celldefine
module RDFFSRARX1_RVT (RSTB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 136321, -1
`celldefine
module RDFFSRARX2_RVT (RSTB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 137244, -1
`celldefine
module RDFFSRASRX1_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 138510, -1
`celldefine
module RDFFSRASRX2_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 139776, -1
`celldefine
module RDFFSRASX1_RVT (SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 140630, -1
`celldefine
module RDFFSRASX2_RVT (SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 141484, -1
`celldefine
module RDFFSRSSRX1_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 142402, -1
`celldefine
module RDFFSRSSRX2_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 143312, -1
`celldefine
module RDFFSRX1_RVT (CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 143966, -1
`celldefine
module RDFFSRX2_RVT (CLK, D, NRESTORE, Q, QN, SAVE, Q2);
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 144622, -1
`celldefine
module RDFFX1_RVT (D, CLK, RETN, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 144932, -1
`celldefine
module RDFFX2_RVT (D, CLK, RETN, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 145242, -1
`celldefine
module RSDFFARX1_RVT (D, CLK, RETN, RSTB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  RSTB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 146257, -1
`celldefine
module RSDFFARX2_RVT (D, CLK, RETN, RSTB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  RSTB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 147272, -1
`celldefine
module RSDFFNARX1_RVT (D, CLK, RETN, RSTB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  RSTB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 148287, -1
`celldefine
module RSDFFNARX2_RVT (D, CLK, RETN, RSTB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  RSTB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 149302, -1
`celldefine
module RSDFFNSRARX1_RVT (RSTB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 151201, -1
`celldefine
module RSDFFNSRARX2_RVT (RSTB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 153100, -1
`celldefine
module RSDFFNSRASRNX1_RVT (RSTB, SETB, CLK, D, NRESTORE, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 155897, -1
`celldefine
module RSDFFNSRASRNX2_RVT (RSTB, SETB, CLK, D, NRESTORE, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 158694, -1
`celldefine
module RSDFFNSRASRQX1_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 161573, -1
`celldefine
module RSDFFNSRASRQX2_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 164452, -1
`celldefine
module RSDFFNSRASRX1_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 166954, -1
`celldefine
module RSDFFNSRASRX2_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 169456, -1
`celldefine
module RSDFFNSRASX1_RVT (SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 171118, -1
`celldefine
module RSDFFNSRASX2_RVT (SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 172780, -1
`celldefine
module RSDFFNSRX1_RVT (CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 173866, -1
`celldefine
module RSDFFNSRX2_RVT (CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 174952, -1
`celldefine
module RSDFFNX1_RVT (D, CLK, RETN, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 175546, -1
`celldefine
module RSDFFNX2_RVT (D, CLK, RETN, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 176140, -1
`celldefine
module RSDFFSRARX1_RVT (RSTB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 177748, -1
`celldefine
module RSDFFSRARX2_RVT (RSTB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 179358, -1
`celldefine
module RSDFFSRASRX1_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 181962, -1
`celldefine
module RSDFFSRASRX2_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 184566, -1
`celldefine
module RSDFFSRASX1_RVT (SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 186208, -1
`celldefine
module RSDFFSRASX2_RVT (SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 187850, -1
`celldefine
module RSDFFSRSSRX1_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 190094, -1
`celldefine
module RSDFFSRSSRX2_RVT (RSTB, SETB, CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  RSTB;
    input  SETB;
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 192340, -1
`celldefine
module RSDFFSRX1_RVT (CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 193632, -1
`celldefine
module RSDFFSRX2_RVT (CLK, D, NRESTORE, Q, QN, SAVE, SE, SI, Q2);
    input  CLK;
    input  D;
    input  NRESTORE;
    output Q;
    output QN;
    input  SAVE;
    input  SE;
    input  SI;
    inout  Q2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 194926, -1
`celldefine
module RSDFFX1_RVT (D, CLK, RETN, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 195513, -1
`celldefine
module RSDFFX2_RVT (D, CLK, RETN, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RETN;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 196100, -1
`celldefine
module SDFFARX1_RVT (D, CLK, RSTB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 197149, -1
`celldefine
module SDFFARX2_RVT (D, CLK, RSTB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 198198, -1
`celldefine
module SDFFASRSX1_RVT (D, CLK, RSTB, SETB, SE, SI, Q, QN, SO);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    output SO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 200043, -1
`celldefine
module SDFFASRSX2_RVT (D, CLK, RSTB, SETB, SE, SI, Q, QN, SO);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    output SO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 201888, -1
`celldefine
module SDFFASRX1_RVT (D, CLK, RSTB, SETB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 203393, -1
`celldefine
module SDFFASRX2_RVT (D, CLK, RSTB, SETB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 204898, -1
`celldefine
module SDFFASX1_RVT (D, CLK, SETB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 205955, -1
`celldefine
module SDFFASX2_RVT (D, CLK, SETB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 207012, -1
`celldefine
module SDFFNARX1_RVT (D, CLK, RSTB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 208057, -1
`celldefine
module SDFFNARX2_RVT (D, CLK, RSTB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 209102, -1
`celldefine
module SDFFNASRX1_RVT (D, CLK, RSTB, SETB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 210607, -1
`celldefine
module SDFFNASRX2_RVT (D, CLK, RSTB, SETB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  RSTB;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 212112, -1
`celldefine
module SDFFNASX1_RVT (D, CLK, SETB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 213243, -1
`celldefine
module SDFFNASX2_RVT (D, CLK, SETB, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  SETB;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 214374, -1
`celldefine
module SDFFNX1_RVT (D, CLK, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 215194, -1
`celldefine
module SDFFNX2_RVT (D, CLK, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 216014, -1
`celldefine
module SDFFSSRX1_RVT (CLK, D, RSTB, SETB, SI, SE, Q, QN);
    input  CLK;
    input  D;
    input  RSTB;
    input  SETB;
    input  SI;
    input  SE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 216775, -1
`celldefine
module SDFFSSRX2_RVT (CLK, D, RSTB, SETB, SI, SE, Q, QN);
    input  CLK;
    input  D;
    input  RSTB;
    input  SETB;
    input  SI;
    input  SE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 217536, -1
`celldefine
module SDFFX1_RVT (D, CLK, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 218379, -1
`celldefine
module SDFFX2_RVT (D, CLK, SE, SI, Q, QN);
    input  D;
    input  CLK;
    input  SE;
    input  SI;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219222, -1
`celldefine
module SHFILL128_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219238, -1
`celldefine
module SHFILL1_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219254, -1
`celldefine
module SHFILL2_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219270, -1
`celldefine
module SHFILL3_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219286, -1
`celldefine
module SHFILL64_RVT ();
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219302, -1
`celldefine
module TIEH_RVT (Y);
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219326, -1
`celldefine
module TIEL_RVT (Y);
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219350, -1
`celldefine
module TNBUFFX16_RVT (A, EN, Y);
    input  A;
    input  EN;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 219802, -1
`celldefine
module TNBUFFX1_RVT (A, EN, Y);
    input  A;
    input  EN;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 220226, -1
`celldefine
module TNBUFFX2_RVT (A, EN, Y);
    input  A;
    input  EN;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 220678, -1
`celldefine
module TNBUFFX32_RVT (A, EN, Y);
    input  A;
    input  EN;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 221130, -1
`celldefine
module TNBUFFX4_RVT (A, EN, Y);
    input  A;
    input  EN;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 221582, -1
`celldefine
module TNBUFFX8_RVT (A, EN, Y);
    input  A;
    input  EN;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 222034, -1
`celldefine
module XNOR2X1_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 222481, -1
`celldefine
module XNOR2X2_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 222928, -1
`celldefine
module XNOR3X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 223594, -1
`celldefine
module XNOR3X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 224260, -1
`celldefine
module XOR2X1_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 224707, -1
`celldefine
module XOR2X2_RVT (A1, A2, Y);
    input  A1;
    input  A2;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 225154, -1
`celldefine
module XOR3X1_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 225820, -1
`celldefine
module XOR3X2_RVT (A1, A2, A3, Y);
    input  A1;
    input  A2;
    input  A3;
    output Y;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine
